---
- name: dotnet installation
  hosts: all
  become: yes
  tasks:
    - name: dotnet6 installation
      ansible.builtin.apt:
        name: dotnet6
        state: present
        update_cache: yes
    - name: untar the module
      ansible.builtin.unarchive:
        src: 'dotnet-sdk-7.0.102-linux-x64.tar.gz'
        dest: /tmp
    






