---
- name: install java
  hosts: all
  become: yes
  tasks:
    - name: install jdk
      ansible.builtin.apt:
        name: openjdk-11-jdk
        state: present
        update_cache: true
    - name: downloading the url
      ansible.builtin.get_url:
        url: https://get.jenkins.io/war/2.385/jenkins.war
        dest: /tmp
        mode: '777'
    - name: copy the url
      ansible.builtin.unarchive:
        src: /tmp/jenkins.war
        dest: /tmp
        mode: '777'
